DROP TABLE IF EXISTS T_TT_ITENS_ORDERS;

CREATE TABLE IF NOT EXISTS T_TT_ITENS_ORDERS(
    ID UUID PRIMARY KEY,
    ID_ORDER UUID NOT NULL,
    ID_PRODUCT UUID NOT NULL,
    QT_ITEN INTEGER NOT NULL,
    VL_TOTAL NUMERIC(10,2) NOT NULL
);

ALTER TABLE T_TT_ITENS_ORDERS ADD CONSTRAINT FK_itens_orders FOREIGN KEY (ID_ORDER) REFERENCES T_TT_ORDERS (ID);
ALTER TABLE T_TT_ITENS_ORDERS ADD CONSTRAINT FK_itens_products FOREIGN KEY (ID_PRODUCT) REFERENCES T_TT_PRODUCTS (ID);