DROP TABLE IF EXISTS T_TT_ORDERS;

CREATE TABLE IF NOT EXISTS T_TT_ORDERS(
    ID UUID PRIMARY KEY,
    NR_ORDER INTEGER NOT NULL UNIQUE,
    ID_USER UUID NOT NULL,
    DT_ORDER TIMESTAMP,
    ST_ORDER VARCHAR(30),
    VL_TOTAL NUMERIC(10,2) NOT NULL
);

ALTER TABLE T_TT_ORDERS ADD CONSTRAINT FK_ORDER_USER FOREIGN KEY (ID_USER) REFERENCES T_TT_USERS (ID);